version: "3.8"
services:
  java-api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    container_name: java-api
    depends_on:
      - mongodb
    volumes:
      - ./import.txt:/app/import.txt
    networks:
      external-shared-network:
    links:
      - mongodb
  mongodb:
    image: mongo
    container_name: mongodb
    command:
      - --noauth
    ports:
      - 27017:27017
    volumes:
      - data:/data
    networks:
      external-shared-network:
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      external-shared-network:

volumes:
  data: {}

networks:
  external-shared-network:
    name: sharednetwork
    external: true
